import LoginButton from './components/LoginButton';
import './globals.css'
import { Inter, Montserrat } from 'next/font/google';

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="emerald" className="min-w-full">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
