import './globals.css'
import { Inter, Montserrat } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'ClrDoc | Sell Your Glasses Online',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="emerald" className="min-w-full">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${montserrat.className} bg-gray-100`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
